baseURL = 'https://portfolio.argo.re/'
languageCode = 'en-us'
title = 'Pi Östberg'
theme = 'quint'
summaryLength = 1

publishDir = "../"

[params]
    email = 'ostbergpi@gmail.com'
    css = ["css/custom.css"]
    icon = 'https://raw.githubusercontent.com/ArgoreOfficial/Wyvern/main/resources/icon.png&style=for-the-badge'
    description = 'Systems & Engine Programmer'

[markup.goldmark.renderer]
    unsafe = true

[[params.social]]
    url = "https://github.com/argoreofficial"
    icon = "github"
    name = "Github"

[[params.social]]
    url = "https://argore.itch.io"
    icon = "itchdotio"
    name = "Itch.io"

[[params.social]]
    url = "mailto:ostbergpi@gmail.com"
    icon = "gmail"
    name = "Email"

[[params.social]]
    url = "https://www.linkedin.com/in/pi-östberg/"
    icon = "linkedin"
    name = "Linkedin"
